### ISSUE TITLE
Whole-slide Image Converted By Orthanc gives issue When Display in Viewer

### ISSUE THREAD

**Issue by Malik-Adil** [MGHComputationalPathology/dicom-microscopy-viewer#31]
Whole-slide Image Converted By Orthanc gives issue When Display in Viewer.

![Screenshot from 2019-06-26 13-53-37](https://user-images.githubusercontent.com/20414066/60166029-d2d09480-9819-11e9-87e6-214a5dfd9627.png)

I am converting .tiff image to dicom using Orthanc Dicomizer. with the command having a dataset. 

./OrthancWSIDicomizer Source.tif --dataset=dataset.json

My dataset.json are

`{
  "PatientID": "C123456789",
  "PatientName": "SOME^PATIENT",
  "PatientBirthDate": "19700101",
  "PatientSex": "M",
  "StudyID": "NONE",
  "SeriesNumber": "1",
  "ReferringPhysicianName": "SOME^PHYSICIAN",
  "AccessionNumber": "123456789",
  "Manufacturer": "MyManufacturer",
  "ManufacturerModelName": "MyModel",
  "DeviceSerialNumber": "MySerialNumber",
  "SoftwareVersions": "MyVersion",
  "ImageType": "DERIVED\\PRIMARY\\VOLUME\\NONE",
  "FocusMethod": "AUTO",
  "ExtendedDepthOfField": "NO",
  "AcquisitionContextSequence": [],
  "AcquisitionDuration": "100",
  "ContainerIdentifier": "CI_12345",
  "IssuerOfTheContainerIdentifierSequence": [],
  "ContainerTypeCodeSequence": [],
  "IssuerOfTheContainerIdentifierSequence": [],

  "FrameOfReferenceUID": "",
  "DerivationDescription": "Derived from a lossy compressed image in NDPi format (JPEG baseline, quality factor 80%, compression ratio 9.7:1)",
  "SpecimenDescriptionSequence": [
    {
      "SpecimenIdentifier": "Specimen^Identifier",
      "SpecimenUID": "1.2.276.0.7230010.3.1.4.3252829876.4112.1426166133.871",
      "IssuerOfTheSpecimenIdentifierSequence": [],
      "SpecimenPreparationSequence": []
    }
  ],
  "SpecimenLabelInImage": "NO",
  "BurnedInAnnotation": "NO"
}
`

**Comment by swederik** [comment]
Also posted here: https://github.com/OHIF/Viewers/issues/589

**Comment by mrcolo** [comment]
Would appreciate some help on this issue.

**Comment by hackermd** [comment]
@Malik-Adil According to your [comment](https://github.com/OHIF/Viewers/issues/589#issuecomment-507637614) at OHIF/Viewers#589, it seems that the pixel spacing of (one of) the images is incorrect and the problem seems to be an issue of the conversion software rather than the viewer.
However, we may want to add a few checks and log a meaningful error message.

**Comment by hackermd** [comment]
@Malik-Adil After giving it some further thought, I would be fine with using `baseTotalPixelMatrixColumns / totalPixelMatrixColumns` instead of `pixelSpacing[0] / basePixelSpacing[0]`. It's probably better to define the "resolution" using pixel rather than millimeter unit. @swederik do you have any concerns?
